version: '3.9'

services:
  db:
    image: postgres:15
    container_name: shopapi_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
    ports:
      - "5432:5432"

volumes:
  postgres_data:
